/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadoutRouteImport } from './routes/loadout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutRoute = LoadoutRouteImport.update({
  id: '/loadout',
  path: '/loadout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/supply': typeof SupplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/supply': typeof SupplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/supply': typeof SupplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/loadout'
    | '/login'
    | '/onboarding'
    | '/supply'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/loadout' | '/login' | '/onboarding' | '/supply'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/loadout'
    | '/login'
    | '/onboarding'
    | '/supply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoadoutRoute: typeof LoadoutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SupplyRoute: typeof SupplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadout': {
      id: '/loadout'
      path: '/loadout'
      fullPath: '/loadout'
      preLoaderRoute: typeof LoadoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoadoutRoute: LoadoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SupplyRoute: SupplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
