/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RankRouteImport } from './routes/rank'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MissionLogRouteImport } from './routes/mission-log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadoutRouteImport } from './routes/loadout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'

const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionLogRoute = MissionLogRouteImport.update({
  id: '/mission-log',
  path: '/mission-log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutRoute = LoadoutRouteImport.update({
  id: '/loadout',
  path: '/loadout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/mission-log': typeof MissionLogRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-complete': typeof OrderCompleteRoute
  '/rank': typeof RankRoute
  '/rewards': typeof RewardsRoute
  '/supply': typeof SupplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/mission-log': typeof MissionLogRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-complete': typeof OrderCompleteRoute
  '/rank': typeof RankRoute
  '/rewards': typeof RewardsRoute
  '/supply': typeof SupplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/loadout': typeof LoadoutRoute
  '/login': typeof LoginRoute
  '/mission-log': typeof MissionLogRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-complete': typeof OrderCompleteRoute
  '/rank': typeof RankRoute
  '/rewards': typeof RewardsRoute
  '/supply': typeof SupplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/loadout'
    | '/login'
    | '/mission-log'
    | '/missions'
    | '/onboarding'
    | '/order-complete'
    | '/rank'
    | '/rewards'
    | '/supply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/loadout'
    | '/login'
    | '/mission-log'
    | '/missions'
    | '/onboarding'
    | '/order-complete'
    | '/rank'
    | '/rewards'
    | '/supply'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/loadout'
    | '/login'
    | '/mission-log'
    | '/missions'
    | '/onboarding'
    | '/order-complete'
    | '/rank'
    | '/rewards'
    | '/supply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  LoadoutRoute: typeof LoadoutRoute
  LoginRoute: typeof LoginRoute
  MissionLogRoute: typeof MissionLogRoute
  MissionsRoute: typeof MissionsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  RankRoute: typeof RankRoute
  RewardsRoute: typeof RewardsRoute
  SupplyRoute: typeof SupplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-log': {
      id: '/mission-log'
      path: '/mission-log'
      fullPath: '/mission-log'
      preLoaderRoute: typeof MissionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadout': {
      id: '/loadout'
      path: '/loadout'
      fullPath: '/loadout'
      preLoaderRoute: typeof LoadoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  LoadoutRoute: LoadoutRoute,
  LoginRoute: LoginRoute,
  MissionLogRoute: MissionLogRoute,
  MissionsRoute: MissionsRoute,
  OnboardingRoute: OnboardingRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  RankRoute: RankRoute,
  RewardsRoute: RewardsRoute,
  SupplyRoute: SupplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
